Aspire Budgeting.xcodeproj/project.pbxproj, Aspire Budgeting.xcodeproj/xcshareddata/xcschemes/Aspire Budgeting.xcscheme, Aspire Budgeting/AppDelegate.swift, Aspire Budgeting/ContentView.swift, Aspire Budgeting/Facilities/GoogleDriveManager.swift, Aspire Budgeting/Facilities/GoogleSDKCredentials.swift, Aspire Budgeting/Facilities/ObjectFactory.swift, Aspire Budgeting/Facilities/UserManager.swift, Aspire Budgeting/Models/User.swift, Aspire Budgeting/SceneDelegate.swift, Aspire Budgeting/Views/GoogleSignInButton.swift, Aspire Budgeting/Views/SignInView.swift, Aspire BudgetingTests/GoogleSDKCredentialsTests.swift, Aspire BudgetingTests/Resources/bad_credentials.plist, Aspire BudgetingTests/Resources/credentials.plist, Aspire BudgetingTests/UserManagerTests.swift, Podfile, Podfile.lock
Primitive implementation of fetching files list done.
=> Added tests and Object Factory

Aspire Budgeting.xcodeproj/project.pbxproj, Aspire Budgeting/Facilities/GoogleSheetsManager.swift, Aspire Budgeting/Models/DashboardCategoryRow.swift, Aspire Budgeting/Models/DashboardGroupsAndCategories.swift, Aspire Budgeting/Views/DashboardRow.swift, Aspire Budgeting/Views/DashboardView.swift, Aspire BudgetingTests/GoogleSheetsManagerTests.swift, Aspire BudgetingTests/MockFile.swift, Aspire BudgetingTests/UserManagerTests.swift
Refactoring and fixing tests for SheetsManager
=> Refactoring SheetsManager

Aspire Budgeting.xcodeproj/project.pbxproj, Aspire Budgeting/ContentView.swift, Aspire Budgeting/Facilities/GoogleSheetsManager.swift, Aspire Budgeting/Facilities/LocalAuthorizationManager.swift, Aspire Budgeting/Facilities/ObjectFactory.swift, Aspire Budgeting/Facilities/StateManager.swift, Aspire Budgeting/Facilities/UserManager.swift, Aspire Budgeting/Models/File.swift, Aspire Budgeting/Models/User.swift, Aspire Budgeting/SceneDelegate.swift, Aspire Budgeting/Views/FaceIDView.swift, Aspire Budgeting/Views/FileSelectorView.swift, Aspire BudgetingTests/GoogleSheetsManagerTests.swift, Aspire BudgetingTests/UserManagerTests.swift
This PR will bookmark the selected sheet and load it on app launch and also introduces a more robust state handler
=> Bookmarking Selected Sheet

Aspire Budgeting/Facilities/LocalAuthorizationManager.swift, Aspire Budgeting/SceneDelegate.swift
Now will ask for FaceID when entering foreground
=> FaceID foreground fix

Aspire Budgeting/Facilities/GoogleSheetsManager.swift, Aspire BudgetingTests/GoogleSheetsManagerTests.swift
This PR improves the test suite
=> Improving test suite

Aspire Budgeting.xcodeproj/project.pbxproj, Aspire Budgeting/Facilities/StateManager.swift, Aspire BudgetingTests/StateManagerTests.swift
This PR improves the state machine
=> Improved statemachine

Aspire Budgeting/Views/Dashboard/DashboardRow.swift, Aspire Budgeting/Views/FaceIDView.swift
=> New FaceID view 

Aspire Budgeting/Views/FileSelectorView.swift
Fixes weird Nav Bar issue probably a SwiftUI bug on first launch
=> Fixed NavBar issue on first launch

Aspire Budgeting/Facilities/Colors.swift, Aspire Budgeting/Views/Dashboard/DashboardRow.swift, Aspire Budgeting/Views/Dashboard/ExpandedCardView.swift
Budgeted text has a yellow gradient now
=> Budgeted text is now yellow

Aspire Budgeting.xcodeproj/project.pbxproj, Aspire Budgeting/Facilities/AspireFonts.swift, Aspire Budgeting/Views/Dashboard/CollapsedCardView.swift, Aspire Budgeting/Views/Dashboard/DashboardRow.swift, Aspire Budgeting/Views/Dashboard/ExpandedCardView.swift, Aspire Budgeting/Views/GradientTextView.swift
Introduced GradientTextView class and DashboardRow now uses GradientTextView
=> GradientTextView class

Aspire Budgeting/Facilities/GoogleSheetsManager.swift
Fixing bug where Aspire v3 sheets were not saved as default sheets
=> Getting the version correctly and remembering version 3 sheets

Aspire Budgeting.xcodeproj/project.pbxproj, Aspire Budgeting/Facilities/AspireOSLogs.swift, Aspire Budgeting/Facilities/GoogleDriveManager.swift, Aspire Budgeting/Facilities/GoogleSDKCredentials.swift, Aspire Budgeting/Facilities/GoogleSheetsManager.swift, Aspire Budgeting/Facilities/LocalAuthorizationManager.swift, Aspire Budgeting/Facilities/StateManager.swift, Aspire Budgeting/Facilities/UserManager.swift, Aspire Budgeting/Models/DashboardMetadata.swift, Aspire BudgetingTests/GoogleSheetsManagerTests.swift
=> Adding os_log

Aspire Budgeting/Facilities/GoogleSheetsManager.swift, Aspire BudgetingTests/DashboardMetadataTests.swift, Aspire BudgetingTests/GoogleSheetsManagerTests.swift
Some minor code change to get the tests to pass.
=> Fixing tests

Aspire Budgeting.xcodeproj/project.pbxproj, Aspire Budgeting.xcodeproj/xcshareddata/xcschemes/Aspire Budgeting.xcscheme, Aspire Budgeting/ContentView.swift, Aspire Budgeting/Facilities/AppCoordinator.swift, Aspire Budgeting/Facilities/LocalAuthorizationManager.swift, Aspire Budgeting/Facilities/ObjectFactory.swift, Aspire Budgeting/Facilities/StateManager.swift, Aspire Budgeting/Facilities/UserManager.swift, Aspire Budgeting/SceneDelegate.swift, Aspire Budgeting/Views/AccountBalancesView.swift, Aspire Budgeting/Views/Dashboard/DashboardView.swift, Aspire Budgeting/Views/FaceIDView.swift, Aspire BudgetingTests/StateManagerTests.swift
This PR introduces the app coordinator and refactors the StateManager
=> Introducing App Coordinator

Aspire Budgeting.xcodeproj/project.pbxproj, Aspire Budgeting/Facilities/Images.swift, Aspire Budgeting/SceneDelegate.swift, Aspire Budgeting/Views/FileSelectorView.swift, Aspire Budgeting/Views/LoadingView.swift
Introducing the new LoadingView
=> New LoadingView

Aspire Budgeting.xcodeproj/project.pbxproj, Aspire Budgeting/Facilities/AppCoordinator.swift, Aspire Budgeting/Facilities/AppDefaults.swift, Aspire Budgeting/Facilities/GoogleContentManager.swift, Aspire Budgeting/Facilities/GoogleSheetsManager.swift, Aspire Budgeting/Facilities/ObjectFactory.swift, Aspire Budgeting/Facilities/StateManager.swift, Aspire Budgeting/Models/DashboardMetadata.swift, Aspire Budgeting/ViewModels/DashboardViewModel.swift, Aspire Budgeting/ViewModels/FileSelectorViewModel.swift, Aspire Budgeting/Views/AspireMasterView.swift, Aspire Budgeting/Views/Dashboard/DashboardView.swift, Aspire Budgeting/Views/ErrorBannerView.swift, Aspire Budgeting/Views/FileSelectorView.swift, Aspire BudgetingTests/GoogleContentManagerTests.swift, Aspire BudgetingTests/GoogleSheetsManagerTests.swift, Aspire BudgetingTests/StateManagerTests.swift
Refactors file reading and writing mechanism
=> File reading and writing

Aspire Budgeting.xcodeproj/project.pbxproj, Aspire Budgeting/Assets.xcassets/tabBarColor.colorset/Contents.json, Aspire Budgeting/Assets.xcassets/tabBarItemDefaultTintColor.colorset/Contents.json, Aspire Budgeting/Assets.xcassets/tabBarItemSelectedTintColor.colorset/Contents.json, Aspire Budgeting/Facilities/Colors.swift, Aspire Budgeting/PreviewProvider/MockProvider.swift, Aspire Budgeting/Views/AspireMasterView.swift, Aspire Budgeting/Views/Dashboard/DashboardView.swift, Aspire Budgeting/Views/TabBarView/ProminentTabBarItemView.swift, Aspire Budgeting/Views/TabBarView/TabBarItemView.swift, Aspire Budgeting/Views/TabBarView/TabBarView.swift
This PR introduces a new TabBarView
=> New TabBarView

Aspire Budgeting/Views/Dashboard/DashboardView.swift, Aspire Budgeting/Views/LoadingView.swift
The LoadingView will now display based on the height provided
=> Loading View height adjustment

Aspire Budgeting/Views/TabBarView/TabBarView.swift
Arranges the children of the tab bar in the center
=> TabBar layout adjustment

Aspire Budgeting/Models/AspireNumber.swift, Aspire Budgeting/ViewModels/DashboardViewModel.swift, Aspire Budgeting/Views/AspireMasterView.swift, Aspire Budgeting/Views/AspireNavigationBar.swift, Aspire Budgeting/Views/AspireSegmentedView.swift, Aspire Budgeting/Views/CardView/CardListView.swift, Aspire Budgeting/Views/CardView/CardView.swift, Aspire Budgeting/Views/Dashboard/DashboardView.swift, Aspire Budgeting/Views/TabBarView/TabBarView.swift
The CardList will now show real data
=> Cards with real data

.travis.yml, Aspire Budgeting.xcodeproj/project.pbxproj, Aspire Budgeting.xcodeproj/xcshareddata/xcschemes/Aspire Budgeting.xcscheme, Aspire Budgeting/Models/AspireNumber.swift, Aspire Budgeting/PreviewProvider/MockProvider.swift, Aspire Budgeting/ViewModels/DashboardViewModel.swift, Aspire Budgeting/Views/AspireNumberView.swift, Aspire Budgeting/Views/AspireProgressBar.swift, Aspire Budgeting/Views/CardView/CardView.swift, Aspire Budgeting/Views/CategoryDetailsView.swift, fastlane/Fastfile
=> Category Details

Aspire Budgeting/ContentView.swift
Removing unnecessary animations that cause problems
=> Removed unnecessary animations

Aspire Budgeting.xcodeproj/project.pbxproj, Aspire Budgeting.xcodeproj/xcshareddata/xcschemes/Aspire Budgeting.xcscheme, Aspire Budgeting/ViewModels/DashboardViewModel.swift, Aspire Budgeting/Views/AspireMasterView.swift, Aspire Budgeting/Views/AspireNumberView.swift, Aspire Budgeting/Views/CategoryDetailsView.swift, Aspire Budgeting/Views/CategoryListView.swift, Aspire Budgeting/Views/Dashboard/DashboardView.swift
Ability to search and filter categories
=> Search Categories

Aspire Budgeting.xcodeproj/project.pbxproj, Aspire Budgeting/Views/BannerView.swift, Aspire Budgeting/Views/CategoryDetailsView.swift
=> Creating standalone BannerView

Aspire Budgeting.xcodeproj/project.pbxproj, Aspire Budgeting/Facilities/AppCoordinator.swift, Aspire Budgeting/Facilities/GoogleContentManager.swift, Aspire Budgeting/Facilities/GoogleSheetsManager.swift, Aspire Budgeting/Models/AccountBalances.swift, Aspire Budgeting/Models/Dashboard.swift, Aspire Budgeting/Views/AccountBalancesView.swift, Aspire BudgetingTests/GoogleContentManagerTests.swift
=> Cleaning up code

Aspire Budgeting/Facilities/GoogleContentManager.swift, Aspire Budgeting/Facilities/GoogleSheetsManager.swift, Aspire BudgetingTests/GoogleContentManagerTests.swift
Trying to cache version if already available
=> Attempt to read version one time

Aspire Budgeting/Facilities/AppDefaults.swift
Fixes a bug that occurs when the app is updated to v2
=> Crash fixed when app is updated

Aspire Budgeting/AppDelegate.swift
File log will now show context and log file name added
=> File log will now show context and log file name added

Aspire Budgeting.xcodeproj/project.pbxproj, Aspire Budgeting/Facilities/AppCoordinator.swift, Aspire Budgeting/Facilities/GoogleContentManager.swift, Aspire Budgeting/Facilities/GoogleSheetsManager.swift, Aspire Budgeting/Models/AddTransactionMetadata.swift, Aspire Budgeting/ViewModels/AddTransactionViewModel.swift, Aspire Budgeting/Views/AddTransactionView.swift, Aspire Budgeting/Views/AspireMasterView.swift, Aspire Budgeting/Views/AspireTextField.swift, Aspire Budgeting/Views/BannerView.swift, Aspire Budgeting/Views/CategoryDetailsView.swift, Aspire BudgetingTests/GoogleContentManagerTests.swift
Creates the Add Transactions view
=> Add Transactions View

Aspire Budgeting/Facilities/AppCoordinator.swift, Aspire Budgeting/Facilities/GoogleContentManager.swift, Aspire Budgeting/Models/AddTransactionMetadata.swift, Aspire BudgetingTests/GoogleContentManagerTests.swift
Sets up meta data required to add transactions
=> Fetch Transaction Accounts and Categories

Aspire Budgeting/Facilities/FileValidator.swift, Aspire Budgeting/Facilities/GoogleContentManager.swift
Enables support for sheet 3.3 #129
=> Support for 3.3

Aspire Budgeting.xcodeproj/project.pbxproj, Aspire Budgeting/Facilities/AppCoordinator.swift, Aspire Budgeting/ViewModels/AccountBalancesViewModel.swift, Aspire Budgeting/ViewModels/DashboardViewModel.swift, Aspire Budgeting/ViewModels/ViewModel.swift, Aspire Budgeting/Views/AccountBalancesView.swift, Aspire Budgeting/Views/Dashboard/DashboardView.swift, Aspire BudgetingTests/ViewModelTests.swift
Delivers generic view models for better code reuse
=> Generic View Models

Aspire Budgeting/Facilities/AppCoordinator.swift, Aspire Budgeting/ViewModels/AddTransactionViewModel.swift, Aspire Budgeting/Views/AddTransactionView.swift, Aspire Budgeting/Views/AspireMasterView.swift
Show list of Accounts and Categories while adding a trx
=> Show list of Accounts and Categories while adding a trx

Aspire Budgeting.xcodeproj/project.pbxproj, Aspire Budgeting/ContentView.swift, Aspire Budgeting/Facilities/AppCoordinator.swift, Aspire Budgeting/Facilities/GoogleContentManager.swift, Aspire Budgeting/Facilities/GoogleSheetsManager.swift, Aspire Budgeting/Facilities/ValueRangeCreator.swift, Aspire Budgeting/Models/Transaction.swift, Aspire Budgeting/SceneDelegate.swift, Aspire Budgeting/ViewModels/AddTransactionViewModel.swift, Aspire Budgeting/Views/AddTransactionView.swift, Aspire BudgetingTests/GoogleContentManagerTests.swift, Aspire BudgetingTests/GoogleSheetsManagerTests.swift
Enables adding transaction to the sheet
=> Adding Transaction

Aspire Budgeting/Facilities/GoogleSheetsManager.swift, Aspire BudgetingTests/GoogleSheetsManagerTests.swift
=> Adding missing tests

Aspire Budgeting/Facilities/AppCoordinator.swift, Aspire Budgeting/Facilities/GoogleContentManager.swift, Aspire Budgeting/ViewModels/AddTransactionViewModel.swift, Aspire Budgeting/Views/AddTransactionView.swift, Aspire BudgetingTests/GoogleContentManagerTests.swift
Displays a success/error message after transaction is added
=> Handle response after adding a transaction

Aspire Budgeting.xcodeproj/project.pbxproj, Aspire Budgeting/Facilities/AppCoordinator.swift, Aspire Budgeting/Facilities/GoogleContentManager.swift, Aspire Budgeting/Facilities/ValueRangeCreator.swift, Aspire Budgeting/Models/Transaction.swift, Aspire Budgeting/ViewModels/TransactionsViewModel.swift, Aspire Budgeting/Views/AddTransactionView.swift, Aspire Budgeting/Views/AspireMasterView.swift, Aspire Budgeting/Views/TransactionsView.swift, Aspire BudgetingTests/GoogleContentManagerTests.swift
This PR implements ability to Fetch and Display Transactions
=> Ability to Fetch and Display transactions

Aspire Budgeting/Models/Transaction.swift, Aspire Budgeting/ViewModels/TransactionsViewModel.swift, Aspire Budgeting/Views/TransactionsView.swift
This PR adds the ability to search through transactions
=> Ability to search transactions

Aspire Budgeting/Assets.xcassets/expenseGreen.colorset/Contents.json, Aspire Budgeting/Assets.xcassets/expenseRed.colorset/Contents.json, Aspire Budgeting/Facilities/Colors.swift, Aspire Budgeting/ViewModels/TransactionsViewModel.swift, Aspire Budgeting/Views/TransactionsView.swift
=> Transactions New UI

Aspire Budgeting/Facilities/Images.swift, Aspire Budgeting/Views/AddTransactionView.swift, Aspire Budgeting/Views/AspireTextField.swift
Cleaning up AspireTextField and using it for amount field on AddTransactionView
=> Refactoring AspireTextField

Aspire Budgeting.xcodeproj/xcshareddata/xcschemes/Aspire Budgeting.xcscheme, Aspire Budgeting/Facilities/Images.swift, Aspire Budgeting/Views/AddTransactionView.swift, Aspire Budgeting/Views/AspireTextField.swift
Improves visual feel to input elements on add transaction view
=> UI improvements to inout fields on Add Transaction View

Aspire Budgeting.xcodeproj/project.pbxproj, Aspire Budgeting/Facilities/AppCoordinator.swift, Aspire Budgeting/Facilities/AppDefaults.swift, Aspire Budgeting/Facilities/StateManager.swift, Aspire Budgeting/ViewModels/SettingsViewModel.swift, Aspire Budgeting/Views/AspireMasterView.swift, Aspire Budgeting/Views/SettingsView.swift
PR adds the ability to change sheets
=> Change Sheet

Aspire Budgeting.xcodeproj/project.pbxproj, Aspire Budgeting/AppDelegate.swift, Aspire Budgeting/Facilities/AppCoordinator.swift, Aspire Budgeting/Views/SettingsView.swift, Aspire Budgeting/Views/ShareSheet.swift
Adds the ability to export logs
=> Exporting Logs

Aspire Budgeting/Facilities/AppCoordinator.swift, Aspire Budgeting/ViewModels/DashboardViewModel.swift, Aspire Budgeting/ViewModels/TransactionsViewModel.swift, Aspire Budgeting/Views/TransactionsView.swift
Refactors Transactions with using publishers
=> Fetching Transactions w/ Publishers

Aspire Budgeting/Facilities/AppCoordinator.swift, Aspire Budgeting/Views/AspireMasterView.swift, Aspire Budgeting/Views/SettingsView.swift
Implements Settings and Change Sheet with publishers
=> Settings and Change Sheet working

Aspire Budgeting/Facilities/AppCoordinator.swift, Aspire Budgeting/Facilities/GoogleContentManager.swift, Aspire Budgeting/ViewModels/AddTransactionViewModel.swift, Aspire Budgeting/Views/AddTransactionView.swift
Fixes Add Transactions with publishers
=> Add Transactions working with Publisher

Aspire Budgeting.xcodeproj/project.pbxproj, Aspire Budgeting/Facilities/AppCoordinator.swift, Aspire Budgeting/Facilities/GoogleContentManager.swift, Aspire Budgeting/Facilities/ValueRangeCreator.swift, Aspire Budgeting/Models/CategoryTransfer.swift, Aspire Budgeting/Models/Dashboard.swift, Aspire Budgeting/Models/DashboardCategory.swift, Aspire Budgeting/Models/TrxCategory.swift, Aspire Budgeting/PreviewProvider/MockProvider.swift, Aspire Budgeting/ViewModels/CategoryTransferViewModel.swift, Aspire Budgeting/ViewModels/DashboardViewModel.swift, Aspire Budgeting/Views/AspireNavigationBar.swift, Aspire Budgeting/Views/AspireTextField.swift, Aspire Budgeting/Views/CategoryDetailsView.swift, Aspire Budgeting/Views/CategoryListView.swift, Aspire Budgeting/Views/CategoryTransferView.swift, Aspire Budgeting/Views/Dashboard/DashboardCardView.swift, Aspire Budgeting/Views/Dashboard/DashboardRow.swift
This PR adds the ability to perform a category transfer
=> Setting up Category Transfer

Aspire Budgeting/Views/AspireNavigationBar.swift
This PR changes the Category Transfer from popover to sheet presentation
=> Fixing iPad Popover issue

Aspire Budgeting/ViewModels/TransactionsViewModel.swift
Fixes unnecessary error pop on Transactions view
=> Fixing error handling for Transactions

Aspire Budgeting/Views/TabBarView/TabBarView.swift
=> TabBar Add transaction fixed on iOS 15
